#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/launch_app

- name: Run the backend application
  docker_container:
    name: my_app
    image: my_app_image:latest  # Remplace avec l'image de ton application
    state: started
    restart_policy: always
    networks:
      - name: my_app_network
    ports:
      - "8080:80"
