#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/launch_proxy

- name: Run NGINX proxy container
  docker_container:
    name: my_proxy
    image: nginx:latest
    state: started
    restart_policy: always
    networks:
      - name: my_app_network
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Remplace avec ta configuration NGINX locale
