name: CI devops 2024
on:
  push:
    branches: 
      - main
      
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn clean verify --file simple-api/pom.xml
    # Job pour construire et pousser les images Docker
  build-and-push-docker-image:
    needs: test-backend  # Ce job s'exécute après que les tests du backend aient réussi
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Connexion à Docker Hub avec les secrets
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

      # Étape pour construire et pousser l'image Docker pour le backend
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api  # Répertoire contenant le Dockerfile du backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          # Publier uniquement lorsque le commit est sur la branche 'main'
          push: ${{ github.ref == 'refs/heads/main' }}

      # Étape pour construire et pousser l'image Docker pour la base de données
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database  # Répertoire contenant le Dockerfile de la base de données
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          # Publier uniquement lorsque le commit est sur la branche 'main'
          push: ${{ github.ref == 'refs/heads/main' }}

      # Étape pour construire et pousser l'image Docker pour le serveur HTTP
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./http-server  # Répertoire contenant le Dockerfile du serveur HTTP
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          # Publier uniquement lorsque le commit est sur la branche 'main'
          push: ${{ github.ref == 'refs/heads/main' }}
